# _*_coding:utf-8_*_
#function                   describe
#asb(number)                返回数字的绝对值
#cath.sqrt(number)          返回平方根，也可应用于复数
#float(object)              将字符串和数字转换为浮点数
#help()                     提供交互式帮助             
#input(prompt)              获取用户输入
#int(object)                将字符串和数字转换为整数
#long(object)               将字符串和数字转换为长整型数      
#math.ceil(number)          返回数的上舍整数，返回值的类型为浮点数
#math.floor(number)         返回数的下舍整数，返回值的类型为浮点数
#math.sqrt(number)          返回平方根，不适用于复数
#pow(x.y)                   返回x的y次幂
#raw_input(prompt)          获取用户输入，结果被看作原始字符串   
#repr(objiect)              返回值的字符串表示形式
#round(numbewr[.ndigits])   根据给定的精度对数字进行四舍五入
#str(object)                将值转换为字符串